server:
  port: 8030
spring:
  application:
    name: gateway
  redis:
    host: ${SPRING_REDIS_HOST:122.51.158.110}
    database: 4
    password: ${SPRING_REDIS_PASSWORD:LyzavGmsILOblYbN78DiWGzOhRPgaVtG}
    port: ${SPRING_REDIS_PORT:11954}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
#              - http://www.0moe.cn
#              - https://www.0moe.cn
#              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: auth
          uri: http://auth.dev.svc.cluster.local:8010
          predicates:
            - Path=/auth/**
        - id: iam
          uri: http://iam.dev.svc.cluster.local:8020
          predicates:
            - Path=/iam/**
        - id: lsmv
          uri: lb://lsmv
          predicates:
            - Path=/lsmv/**
        - id: social
          uri: lb://social
          predicates:
            - Path=/social/**

        - id: auth-dawn
          uri: lb://auth-dawn
          predicates:
            - Path=/auth-dawn/**
        - id: iam-dawn
          uri: http://10.8.0.6:8021
          predicates:
            - Path=/iam-dawn/**
dubbo:
  registry:
    address: consul://${SPRING_CLOUD_CONSUL_HOST:consul.resource.0moe.cn}:${SPRING_CLOUD_CONSUL_PORT:80}?token=${SPRING_CLOUD_CONSUL_ACL_TOKEN:bef68e54-6195-2c65-227d-a840f9f745ee}
  consumer:
    check: false