# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: action-maven-publish
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        # Username (not email!) for your Nexus repository manager account
        nexus_username: 571863559
        # Password for your Nexus account
        nexus_password: Asd.54188+
        # Nexus server ID as specified in your project's `nexus-staging-maven-plugin` and `distributionManagement` configurations
        server_id: docker-tencent
        # Additional arguments to pass to the Maven command
        maven_goals_phases: mvn clean package docker:build
        maven_args: -DpushImage -Dmaven.test.skip=true
